---
# tasks file for win_ad_user
 - name: add user to AD
   win_domain_user:
     name: "{{ item.name }}"
     firstname: "{{ item.firstname }}"
     surname: "{{ item.surname }}"
     password: "{{ item.password }}"
     state: present
   with_items:
     - "{{ user_info }}"
